/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zendesk1;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karan
 */
//This class handles the UI of the application. There is some Auto-generated code in this class.
public class UserInterface extends javax.swing.JFrame {

    public DefaultTableModel model; //table model
    int pageNumber = 1;             //to keep track of pages while pagination happens
    boolean nextPage = false;       //variables to check next and prev page exits
    boolean prevPage = false;
    public TicketList ticketList;

    /**
     * Creates new form NewJFrame
     */
    public UserInterface() {
        initComponents();
        //remove tabbedPane tabs.
        this.jTabbedPane1.remove(1);
        this.jTabbedPane1.remove(1);
    }

    public void dialogBoxMessageDisplay(Object message) {
        JOptionPane.showMessageDialog(this, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //auto-generated code starts here, editing this code will result in UI failure, you can ignore if you like---------
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LoginPanel = new javax.swing.JPanel();
        retrieveListButton = new javax.swing.JButton();
        uNameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passUI = new javax.swing.JTextField();
        uNameUI = new javax.swing.JTextField();
        welcome = new javax.swing.JLabel();
        ticketOfficerLabel = new javax.swing.JLabel();
        MultipleTicketPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pageNumberUI = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        urlField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        urlLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        pleaseWaitLabel = new javax.swing.JLabel();
        SingleTicketPanel = new javax.swing.JPanel();
        ticketIdLabel = new javax.swing.JLabel();
        ticketIdTextField = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();
        subjectTextField = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        statusLabel = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        submitterLabel = new javax.swing.JLabel();
        enterIdLabel = new javax.swing.JLabel();
        enterIdTextField = new javax.swing.JTextField();
        enterIdButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        submitterIdTextField = new javax.swing.JTextField();
        tagsTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        tagsLabel = new javax.swing.JLabel();
        createdAtLabel = new javax.swing.JLabel();
        createdAtTextField = new javax.swing.JTextField();
        updatedAtLabel = new javax.swing.JLabel();
        updatedAtTextField = new javax.swing.JTextField();
        viaLabel = new javax.swing.JLabel();
        viaTextField = new javax.swing.JTextField();
        urlTextField = new javax.swing.JTextField();
        subjectLabel1 = new javax.swing.JLabel();
        backToLoginButton = new javax.swing.JButton();
        requesteerIdTextField = new javax.swing.JTextField();
        submitterLabel1 = new javax.swing.JLabel();
        organizationIdTextField = new javax.swing.JTextField();
        submitterLabel2 = new javax.swing.JLabel();
        collabIdLabel = new javax.swing.JLabel();
        collabIdTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setEnabled(false);

        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retrieveListButton.setText("Retrieve List");
        retrieveListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveListButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(retrieveListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        uNameLabel.setText("Password:");
        LoginPanel.add(uNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, 30));

        passLabel.setText("Username/Email:");
        LoginPanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 30));
        LoginPanel.add(passUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 180, 40));
        LoginPanel.add(uNameUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 180, 40));

        welcome.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Welcome to Zendesk's - The Soft Croissant subdomain.");
        welcome.setToolTipText("");
        LoginPanel.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 740, 120));

        ticketOfficerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ticketOfficerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ticketOfficerLabel.setText("This is Ticket Officer - The Ticket Viewer.");
        LoginPanel.add(ticketOfficerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 410, 80));

        jTabbedPane1.addTab("Login", LoginPanel);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("This view shows all the tickets. ");
        jLabel2.setLocation(new java.awt.Point(0, 10));

        nextButton.setText("Next");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.setEnabled(false);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        urlField.setEditable(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Subject", "Created At", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        urlLabel.setLabelFor(urlField);
        urlLabel.setText("URL:");

        instructionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        instructionLabel.setForeground(new java.awt.Color(255, 0, 51));
        instructionLabel.setText("Double Click on any Ticket to view more information about it.");

        pleaseWaitLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pleaseWaitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pleaseWaitLabel.setText("Please Wait...");
        pleaseWaitLabel.setLocation(new java.awt.Point(0, 10));

        javax.swing.GroupLayout MultipleTicketPanelLayout = new javax.swing.GroupLayout(MultipleTicketPanel);
        MultipleTicketPanel.setLayout(MultipleTicketPanelLayout);
        MultipleTicketPanelLayout.setHorizontalGroup(
            MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultipleTicketPanelLayout.createSequentialGroup()
                .addGroup(MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MultipleTicketPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MultipleTicketPanelLayout.createSequentialGroup()
                                .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MultipleTicketPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(instructionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(MultipleTicketPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pageNumberUI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(previousButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pleaseWaitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        MultipleTicketPanelLayout.setVerticalGroup(
            MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultipleTicketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MultipleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(pageNumberUI, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(pleaseWaitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("View-All-tickets", MultipleTicketPanel);

        ticketIdLabel.setLabelFor(ticketIdTextField);
        ticketIdLabel.setText("Ticket Id:");

        ticketIdTextField.setEditable(false);

        subjectLabel.setText("Subject:");

        subjectTextField.setEditable(false);

        descLabel.setText("Description:");

        descTextArea.setEditable(false);
        descTextArea.setColumns(20);
        descTextArea.setLineWrap(true);
        descTextArea.setRows(5);
        jScrollPane2.setViewportView(descTextArea);

        statusLabel.setText("Status:");

        statusTextField.setEditable(false);

        submitterLabel.setText("Submitter Id:");

        enterIdLabel.setText("Enter Ticket Id to view information:");

        enterIdButton.setText("Retrieve Ticket");
        enterIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterIdButtonActionPerformed(evt);
            }
        });

        submitterIdTextField.setEditable(false);

        tagsTextField.setEditable(false);
        tagsTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        typeLabel.setLabelFor(ticketIdTextField);
        typeLabel.setText("Type:");

        typeTextField.setEditable(false);

        tagsLabel.setText("Tags:");

        createdAtLabel.setText("Created at:");

        createdAtTextField.setEditable(false);

        updatedAtLabel.setText("Updated At:");

        updatedAtTextField.setEditable(false);

        viaLabel.setText("Via-Channel:");

        viaTextField.setEditable(false);

        urlTextField.setEditable(false);

        subjectLabel1.setText("URL:");

        backToLoginButton.setText("Back to Login");
        backToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginButtonActionPerformed(evt);
            }
        });

        requesteerIdTextField.setEditable(false);

        submitterLabel1.setText("Requesteer Id:");

        organizationIdTextField.setEditable(false);

        submitterLabel2.setText("Organization Id:");

        collabIdLabel.setText("Collaborators Ids:");

        collabIdTextField.setEditable(false);
        collabIdTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout SingleTicketPanelLayout = new javax.swing.GroupLayout(SingleTicketPanel);
        SingleTicketPanel.setLayout(SingleTicketPanelLayout);
        SingleTicketPanelLayout.setHorizontalGroup(
            SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(enterIdLabel)
                        .addGap(8, 8, 8)
                        .addComponent(enterIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(enterIdButton))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ticketIdLabel)
                        .addGap(296, 296, 296)
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(viaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(viaLabel)))
                            .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submitterLabel)
                                    .addComponent(tagsLabel))
                                .addGap(18, 18, 18)
                                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                        .addComponent(submitterIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(submitterLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(requesteerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(submitterLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(organizationIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SingleTicketPanelLayout.createSequentialGroup()
                                            .addComponent(createdAtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(45, 45, 45)
                                            .addComponent(updatedAtLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(updatedAtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                    .addComponent(subjectLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                    .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descLabel)
                                        .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SingleTicketPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ticketIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createdAtLabel))
                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(collabIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(collabIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(backToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SingleTicketPanelLayout.setVerticalGroup(
            SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SingleTicketPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitterIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitterLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requesteerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitterLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organizationIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdAtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createdAtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatedAtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatedAtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SingleTicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collabIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collabIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Single-Ticket", SingleTicketPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //end of auto generated code---------------------------------------------------------------------------------------

    //this method is invoked when Retrieve List button is pressed on the Login Screen
    private void retrieveListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveListButtonActionPerformed
        //get the table model from UI
        model = (DefaultTableModel) table.getModel();
        //uNameUI and passUI contains username and password supplied
        ticketList = new TicketList(uNameUI.getText(), passUI.getText());
        //if getTicketPerPage returns positive result enable the UI and update it
        if (ticketList.getTicketsPerPage(pageNumber, 25)) {
            enableUI();
            updateMultiTicketUI();
        }

    }//GEN-LAST:event_retrieveListButtonActionPerformed

    //this method will help update the URL for View-all ticket panel.
    public void updateAddressBar(String url) {
        urlField.setText(url);
    }

    //enables the UI by removing Login Page and adding All Tickets(MultipleTicketPanel) and Single Ticket Page(Single TicketPanel).
    public void enableUI() {
        pleaseWaitLabel.setVisible(false);
        jTabbedPane1.setEnabled(true);
        jTabbedPane1.remove(0);
        jTabbedPane1.add("All Tickets", this.MultipleTicketPanel);
        jTabbedPane1.add("Single Ticket", this.SingleTicketPanel);

    }

    //method for getting a single ticket 
    private void getSingleTicket(long id) {
        try {
            tagsTextField.setText("");
            ticketList.getSingleTicketById(id);
        } catch (ArithmeticException e1) {
            this.dialogBoxMessageDisplay("Sorry, id can only be an Integer. Try Again.");
        }
    }

    //fills the UI of SingleTicketPanel
    public void fillSingleTicketUI(Ticket ticket) {
        ticketIdTextField.setText(Long.toString(ticket.id));
        subjectTextField.setText(ticket.subject);
        descTextArea.setText(ticket.description);
        statusTextField.setText(ticket.status);
        submitterIdTextField.setText(Long.toString(ticket.submitterId));
        viaTextField.setText(ticket.via.channel);
        createdAtTextField.setText(ticket.createdAt);
        updatedAtTextField.setText(ticket.updatedAt);
        typeTextField.setText(ticket.type);
        urlTextField.setText(ticket.url);
        requesteerIdTextField.setText(Long.toString(ticket.requesterId));
        organizationIdTextField.setText(Long.toString(ticket.organizationId));

        //ticket.tags and ticket.collaboratorsIds are arrays
        //if the arrays are empty an appropriate message will be displayed.
        for (int i = 0; i < ticket.tags.length; i++) {
            if (ticket.tags[0].equals("") && (ticket.tags.length == 1)) {
                tagsTextField.setText("No tags Available");
            } else {
                if (i == 0) {
                    tagsTextField.setText(ticket.tags[i]);
                } else {
                    tagsTextField.setText(tagsTextField.getText() + "," + ticket.tags[i]);
                }
            }
        }
        for (int i = 0; i < ticket.collaboratorsIds.length; i++) {
            if (ticket.collaboratorsIds[0] == 0 && ticket.collaboratorsIds.length == 1) {
                collabIdTextField.setText("No collaboratos.");
            } else {
                if (i == 0) {
                    collabIdTextField.setText(Long.toString(ticket.collaboratorsIds[i]));
                } else {
                    collabIdTextField.setText(collabIdTextField.getText() +","+ ticket.collaboratorsIds[i]);
                }
            }
        }
    }

    //this method updates the All tickets UI
    //also checks for prev and next pages and performs actions accordingly.
    private void updateMultiTicketUI() {
        table.getColumnModel().getColumn(0).setPreferredWidth(5);
        table.getColumnModel().getColumn(1).setPreferredWidth(250);
        if (!ticketList.isNextPage()) {
            this.nextButton.setEnabled(false);
        } else {
            this.nextButton.setEnabled(true);
        }
        if (!ticketList.isPrevPage()) {
            this.previousButton.setEnabled(false);
        } else {
            this.previousButton.setEnabled(true);
        }
        pageNumberUI.setText("Page Number: " + Integer.toString(pageNumber));
        pleaseWaitLabel.setVisible(false);
    }

    //this method empty the table on MultiTicketPage
    private void emptyTable() {
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    //next button for All ticket Page invokes this method when clicked.
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        pleaseWaitLabel.setVisible(true);
        if (ticketList.isNextPage()) {
            emptyTable();
            pageNumber++;
            ticketList.getTicketsPerPage(pageNumber, 25);
        }
        updateMultiTicketUI();
    }//GEN-LAST:event_nextButtonActionPerformed

    //next button for All ticket Page invokes this method when clicked.
    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (ticketList.isPrevPage()) {
            emptyTable();
            pageNumber--;
            ticketList.getTicketsPerPage(pageNumber, 25);
        }
        updateMultiTicketUI();
    }//GEN-LAST:event_previousButtonActionPerformed

    //Retrieve Single ticket button on Single Ticket page invokes this method when clicked.
    private void enterIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterIdButtonActionPerformed
        long id;
        try {
            id = Long.parseLong(enterIdTextField.getText());
        } catch (NumberFormatException e1) {
            resetSingleTicketPanel();
            //error message displayed if something other than number is entered.
            this.dialogBoxMessageDisplay("Sorry, id can only have digits in it. Try again.");
            return;
        }
        //call to getSingleTicket method if everything goes well
        getSingleTicket(id);
    }//GEN-LAST:event_enterIdButtonActionPerformed

    //this method enables the functionality of viewing a ticket from table on double click.
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        JTable source = (JTable) evt.getSource();
        //get row number which is clicked
        int row = source.rowAtPoint(evt.getPoint());
        //id is located at column 0 of that row
        long id = Long.parseLong(source.getValueAt(row, 0).toString());
        getSingleTicket(id);
        //switch to single ticket view
        jTabbedPane1.setSelectedIndex(1);
        enterIdTextField.setText(ticketIdTextField.getText());
    }//GEN-LAST:event_tableMouseClicked

    //reset all components of the application
    private void resetAll() {
        jTabbedPane1.removeAll();
        resetLoginPanel();
        resetMultipleTicketPanel();
        resetSingleTicketPanel();
    }

    protected void resetLoginPanel() {
        uNameUI.setText("");
        passUI.setText("");
        jTabbedPane1.add("Login", LoginPanel);
    }

    protected void resetMultipleTicketPanel() {
        emptyTable();
        pageNumber = 1;
        urlField.setText("");
    }

    protected void resetSingleTicketPanel() {
        urlTextField.setText("");
        enterIdTextField.setText("");
        ticketIdTextField.setText("");
        subjectTextField.setText("");
        descTextArea.setText("");
        statusTextField.setText("");
        submitterIdTextField.setText("");
        viaTextField.setText("");
        createdAtTextField.setText("");
        updatedAtTextField.setText("");
        typeTextField.setText("");
        tagsTextField.setText("");
        collabIdTextField.setText("");
        requesteerIdTextField.setText("");
        organizationIdTextField.setText("");
    }

    //invoked by pressening "Back to Login" button
    private void backToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginButtonActionPerformed
        resetAll();
    }//GEN-LAST:event_backToLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MultipleTicketPanel;
    private javax.swing.JPanel SingleTicketPanel;
    private javax.swing.JButton backToLoginButton;
    private javax.swing.JLabel collabIdLabel;
    private javax.swing.JTextField collabIdTextField;
    private javax.swing.JLabel createdAtLabel;
    private javax.swing.JTextField createdAtTextField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JButton enterIdButton;
    private javax.swing.JLabel enterIdLabel;
    private javax.swing.JTextField enterIdTextField;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField organizationIdTextField;
    private javax.swing.JLabel pageNumberUI;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passUI;
    private javax.swing.JLabel pleaseWaitLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField requesteerIdTextField;
    private javax.swing.JButton retrieveListButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel subjectLabel1;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JTextField submitterIdTextField;
    private javax.swing.JLabel submitterLabel;
    private javax.swing.JLabel submitterLabel1;
    private javax.swing.JLabel submitterLabel2;
    private javax.swing.JTable table;
    private javax.swing.JLabel tagsLabel;
    private javax.swing.JTextField tagsTextField;
    private javax.swing.JLabel ticketIdLabel;
    private javax.swing.JTextField ticketIdTextField;
    private javax.swing.JLabel ticketOfficerLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextField;
    private javax.swing.JLabel uNameLabel;
    private javax.swing.JTextField uNameUI;
    private javax.swing.JLabel updatedAtLabel;
    private javax.swing.JTextField updatedAtTextField;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JLabel viaLabel;
    private javax.swing.JTextField viaTextField;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
